In [2]:
import numpy as np
import pandas as pd

In [100]:
print(dict_3)

{'mlm': [50, 28, 38, 44, 38, 40, 33, 40, 28, 36, 42, 48, 38, 34, 27, 48, 38, 25, 48, 26, 34, 28, 36, 25, 29, 50, 38, 31, 45, 26, 27, 32, 36, 50, 31, 37, 31, 48, 25, 34, 43, 32, 29, 29, 34, 43, 30, 50, 39, 28, 38, 47, 33, 37, 33, 30, 40, 41, 31, 27, 48, 39, 40, 44, 39, 43, 27, 42, 37, 38, 28, 39, 37, 38, 29, 42, 33, 39, 43, 44, 44, 46, 42, 38, 42, 45, 38, 34, 30, 34, 44, 48, 45, 34, 39, 27, 27, 44, 48, 27], 'bus': [18, 25, 23, 25, 23, 22, 24, 21, 24, 19, 22, 21, 16, 21, 16, 22, 23, 18, 16, 20, 15, 24, 22, 16, 16, 21, 20, 19, 24, 18, 20, 19, 19, 16, 22, 24, 24, 24, 16, 19, 17, 18, 18, 22, 16, 21, 17, 23, 15, 25, 16, 20, 22, 18, 24, 17, 20, 24, 15, 16, 24, 21, 16, 19, 22, 18, 19, 17, 20, 23, 21, 23, 22, 19, 17, 21, 16, 23, 21, 25, 22, 20, 20, 25, 17, 22, 21, 23, 20, 22, 17, 19, 16, 19, 22, 24, 24, 25, 17, 17], 'moti': [7, 11, 8, 11, 15, 13, 14, 12, 13, 9, 8, 6, 7, 7, 12, 15, 9, 10, 8, 6, 13, 6, 7, 12, 15, 13, 5, 15, 8, 8, 13, 10, 13, 7, 14, 13, 13, 14, 15, 8, 9, 11, 12, 14, 7, 11, 13, 13,

In [121]:
import random
def hundred(m1,m2,b1,b2,mo1,mo2,o1,o2,n4):
    hun = {"mlm": [],"bus": [], "moti": [], "others": [], "clas": []}
    mlm = []
    bus = []
    moti = []
    others = []
    clas = []
    for i in range(0,100):
        n = random.randint(25,50)
        mlm.append(n)
        clas.append(100)
    for i in range(0,100):
        n1 = random.randint(15,25)
        bus.append(n1)
        clas.append(100)
    for i in range(0,100):
        n2 = random.randint(5,15)
        moti.append(n2)
    for i in range(0,100):
        n3 = random.randint(0,5)
        others.append(n3)
        clas.append(20)
    
    hun["mlm"] += mlm
    hun["bus"] += bus
    hun["moti"] += moti
    hun["others"] += others
    hun["clas"] += clas
    return hun
m1=25
m2=50
b1=15
b2=25
mo1=5
mo2=15
o1=0
o2=5
n4=100
m1,m2,b1,b2,mo1,mo2,o1,o2,n4 = 25,50,15,25,5,15,0,5,100
m11,m12,b11,b12,mo11,mo12,o11,o12,n14 = 25,50,15,25,5,15,0,5,100
m21,m22,b21,b22,mo21,mo22,o21,o22,n24 = 25,50,15,25,5,15,0,5,100
m31,m32,b31,b32,mo31,mo32,o31,o32,n34 = 25,50,15,25,5,15,0,5,100
m41,m42,b41,b42,mo41,mo42,o41,o42,n44 = 25,50,15,25,5,15,0,5,100

one = hundred(m1,m2,b1,b2,mo1,mo2,o1,o2,n4)
two1 = hundred(m11,m12,b11,b12,mo11,mo12,o11,o12,n14)
two2 = hundred(m21,m22,b21,b22,mo21,mo22,o21,o22,n24)
two3 = hundred(m31,m32,b31,b32,mo31,mo32,o31,o32,n34)
two4 = hundred(m41,m42,b41,b42,mo41,mo42,o41,o42,n44)

three = [hundred1,hundred]
#print(dicts[0])
mer = {"mlm": [],"bus": [], "moti": [], "others": [], "clas": []}
mlm = []
bus = []
moti = []
others = []
clas = []
for i in dicts:
    mlm.extend((i['mlm']))
    bus.extend((i['bus']))
    moti.extend((i['moti']))
    others.extend((i['others']))
    clas.extend((i['clas']))
mer["mlm"] += mlm
mer["bus"] += bus
mer["moti"] += moti
mer["others"] += others
mer["clas"] += clas
print(len(mer["mlm"]))   

200


In [78]:
import random
def eighty():
    eight = {"mlm": [],"bus": [], "moti": [], "others": []}
    mlm = []
    bus = []
    moti = []
    others = []
    for i in range(0,100):
        n = random.randint(25,40)
        mlm.append(n)
    for i in range(0,100):
        n1 = random.randint(15,25)
        bus.append(n1)
    for i in range(0,100):
        n2 = random.randint(0,15)
        moti.append(n2)
    for i in range(0,100):
        n3 = random.randint(0,15)
        others.append(n3)
    eight["mlm"] += mlm
    eight["bus"] += bus
    eight["moti"] += moti
    eight["others"] += others
    return eight
eighty = eighty()

In [54]:
import random
def sixty():
    six = {"mlm": [],"bus": [], "moti": [], "others": []}
    mlm = []
    bus = []
    moti = []
    others = []
    for i in range(0,100):
        n = random.randint(15,25)
        mlm.append(n)
    for i in range(0,100):
        n1 = random.randint(25,50)
        bus.append(n1)
    for i in range(0,100):
        n2 = random.randint(0,15)
        moti.append(n2)
    for i in range(0,100):
        n3 = random.randint(0,15)
        others.append(n3)
    six["mlm"] += mlm
    six["bus"] += bus
    six["moti"] += moti
    six["others"] += others
    return six
sixty = sixty()

In [55]:
import random
def four():
    four = {"mlm": [],"bus": [], "moti": [], "others": []}
    mlm = []
    bus = []
    moti = []
    others = []
    for i in range(0,100):
        n = random.randint(0,10)
        mlm.append(n)
    for i in range(0,100):
        n1 = random.randint(20,50)
        bus.append(n1)
    for i in range(0,100):
        n2 = random.randint(0,15)
        moti.append(n2)
    for i in range(0,100):
        n3 = random.randint(0,10)
        others.append(n3)
    four["mlm"] += mlm
    four["bus"] += bus
    four["moti"] += moti
    four["others"] += others
    return four
four = four()

In [56]:
import random
def two():
    two = {"mlm": [],"bus": [], "moti": [], "others": []}
    mlm = []
    bus = []
    moti = []
    others = []
    for i in range(0,100):
        n = random.randint(0,2)
        mlm.append(n)
    for i in range(0,100):
        n1 = random.randint(0,10)
        bus.append(n1)
    for i in range(0,100):
        n2 = random.randint(0,10)
        moti.append(n2)
    for i in range(0,100):
        n3 = random.randint(25,50)
        others.append(n3)
    two["mlm"] += mlm
    two["bus"] += bus
    two["moti"] += moti
    two["others"] += others
    return two
two = two()

In [57]:
two = pd.DataFrame(two)
four = pd.DataFrame(four)
sixty = pd.DataFrame(sixty)
eighty = pd.DataFrame(eighty)
hundred = pd.DataFrame(hundred)

In [62]:
two

mlm  bus  moti  others
0     2    1     4      29
1     0    2     4      29
2     1   10     6      44
3     1    1     8      31
4     2    1     5      47
..  ...  ...   ...     ...
95    1    4     7      37
96    2    4    10      48
97    0    4     8      34
98    0    3     1      25
99    0    8     7      42

[100 rows x 4 columns]

In [63]:
two.to_excel("two.xlsx")
four.to_excel("four.xlsx")
sixty.to_excel("sixty.xlsx")
eighty.to_excel("eighty.xlsx")
hundred.to_excel("hundred.xlsx")

In [2]:
import pandas as pd
import random
def hundred():
    hun = {"mlm": [],"bus": [], "moti": [], "others": [], "clas": []}
    mlm = []
    bus = []
    moti = []
    others = []
    clas = []
    for i in range(0,200):
        n = random.randint(25,50)
        hun['mlm'].append(n)
        n1 = random.randint(15,25)
        hun['bus'].append(n1)
        n2 = random.randint(5,15)
        hun['moti'].append(n2)
        n3 = random.randint(25,50)
        hun['others'].append(n3)
        hun['clas'].append(100)
        
        n = random.randint(50,100)
        hun['mlm'].append(n)
        n1 = random.randint(50,100)
        hun['bus'].append(n1)
        n2 = random.randint(0,15)
        hun['moti'].append(n2)
        n3 = random.randint(50,100)
        hun['others'].append(n3)
        hun['clas'].append(100)
        
        n = random.randint(100,200)
        hun['mlm'].append(n)
        n1 = random.randint(50,120)
        hun['bus'].append(n1)
        n2 = random.randint(0,50)
        hun['moti'].append(n2)
        n3 = random.randint(50,100)
        hun['others'].append(n3)
        hun['clas'].append(100)
        
        n = random.randint(100,200)
        hun['mlm'].append(n)
        n1 = random.randint(200,250)
        hun['bus'].append(n1)
        n2 = random.randint(0,100)
        hun['moti'].append(n2)
        n3 = random.randint(200,250)
        hun['others'].append(n3)
        hun['clas'].append(100)
        
        n = random.randint(300,400)
        hun['mlm'].append(n)
        n1 = random.randint(100,200)
        hun['bus'].append(n1)
        n2 = random.randint(0,100)
        hun['moti'].append(n2)
        n3 = random.randint(300,400)
        hun['others'].append(n3)
        hun['clas'].append(100)
    return hun
gg = hundred()
print(len(gg['mlm']))
gg = pd.DataFrame(gg)
gg.to_excel("first_hundred.xlsx")

1000


In [10]:
import random
def hundred():
    hun = {"mlm": [],"bus": [], "moti": [], "others": [], "clas": []}
    mlm = []
    bus = []
    moti = []
    others = []
    clas = []
    for i in range(0,200):
        n = random.randint(15,50)
        hun['mlm'].append(n)
        n1 = random.randint(25,50)
        hun['bus'].append(n1)
        n2 = random.randint(5,15)
        hun['moti'].append(n2)
        n3 = random.randint(25,50)
        hun['others'].append(n3)
        hun['clas'].append(80)
        
        n = random.randint(25,100)
        hun['mlm'].append(n)
        n1 = random.randint(50,100)
        hun['bus'].append(n1)
        n2 = random.randint(0,15)
        hun['moti'].append(n2)
        n3 = random.randint(50,100)
        hun['others'].append(n3)
        hun['clas'].append(80)
        
        n = random.randint(50,200)
        hun['mlm'].append(n)
        n1 = random.randint(100,200)
        hun['bus'].append(n1)
        n2 = random.randint(0,50)
        hun['moti'].append(n2)
        n3 = random.randint(100,200)
        hun['others'].append(n3)
        hun['clas'].append(80)
        
        n = random.randint(100,300)
        hun['mlm'].append(n)
        n1 = random.randint(200,300)
        hun['bus'].append(n1)
        n2 = random.randint(0,100)
        hun['moti'].append(n2)
        n3 = random.randint(200,300)
        hun['others'].append(n3)
        hun['clas'].append(80)
        
        n = random.randint(100,400)
        hun['mlm'].append(n)
        n1 = random.randint(300,400)
        hun['bus'].append(n1)
        n2 = random.randint(0,100)
        hun['moti'].append(n2)
        n3 = random.randint(300,400)
        hun['others'].append(n3)
        hun['clas'].append(80)
    return hun
gg = hundred()
print(len(gg['mlm']))
gg = pd.DataFrame(gg)
gg.to_excel("first_eighty.xlsx")

1000


In [130]:
import random
def hundred():
    hun = {"mlm": [],"bus": [], "moti": [], "others": [], "clas": []}
    mlm = []
    bus = []
    moti = []
    others = []
    clas = []
    for i in range(0,200):
        n = random.randint(25,50)
        hun['bus'].append(n)
        n1 = random.randint(15,25)
        hun['mlm'].append(n1)
        n2 = random.randint(5,15)
        hun['moti'].append(n2)
        n3 = random.randint(0,5)
        hun['others'].append(n3)
        hun['clas'].append(60)
        
        n = random.randint(50,100)
        hun['bus'].append(n)
        n1 = random.randint(25,50)
        hun['mlm'].append(n1)
        n2 = random.randint(0,15)
        hun['moti'].append(n2)
        n3 = random.randint(0,15)
        hun['others'].append(n3)
        hun['clas'].append(60)
        
        n = random.randint(100,200)
        hun['bus'].append(n)
        n1 = random.randint(50,120)
        hun['mlm'].append(n1)
        n2 = random.randint(0,50)
        hun['moti'].append(n2)
        n3 = random.randint(0,50)
        hun['others'].append(n3)
        hun['clas'].append(60)
        
        n = random.randint(200,300)
        hun['bus'].append(n)
        n1 = random.randint(100,200)
        hun['mlm'].append(n1)
        n2 = random.randint(0,100)
        hun['moti'].append(n2)
        n3 = random.randint(0,100)
        hun['others'].append(n3)
        hun['clas'].append(60)
        
        n = random.randint(300,400)
        hun['bus'].append(n)
        n1 = random.randint(100,200)
        hun['mlm'].append(n1)
        n2 = random.randint(0,100)
        hun['moti'].append(n2)
        n3 = random.randint(50,120)
        hun['others'].append(n3)
        hun['clas'].append(60)
    return hun
gg = hundred()
print(len(gg['mlm']))
gg = pd.DataFrame(gg)
gg.to_excel("first_sixty.xlsx")

1000


In [135]:
import random
def hundred():
    hun = {"mlm": [],"bus": [], "moti": [], "others": [], "clas": []}
    mlm = []
    bus = []
    moti = []
    others = []
    clas = []
    for i in range(0,200):
        n = random.randint(0,5)
        hun['mlm'].append(n)
        n1 = random.randint(15,25)
        hun['bus'].append(n1)
        n2 = random.randint(5,15)
        hun['moti'].append(n2)
        n3 = random.randint(0,5)
        hun['others'].append(n3)
        hun['clas'].append(40)
        
        n = random.randint(0,15)
        hun['mlm'].append(n)
        n1 = random.randint(25,50)
        hun['bus'].append(n1)
        n2 = random.randint(0,15)
        hun['moti'].append(n2)
        n3 = random.randint(0,15)
        hun['others'].append(n3)
        hun['clas'].append(40)
        
        n = random.randint(0,50)
        hun['mlm'].append(n)
        n1 = random.randint(50,120)
        hun['bus'].append(n1)
        n2 = random.randint(0,50)
        hun['moti'].append(n2)
        n3 = random.randint(0,50)
        hun['others'].append(n3)
        hun['clas'].append(40)
        
        n = random.randint(0,100)
        hun['mlm'].append(n)
        n1 = random.randint(100,200)
        hun['bus'].append(n1)
        n2 = random.randint(0,100)
        hun['moti'].append(n2)
        n3 = random.randint(0,100)
        hun['others'].append(n3)
        hun['clas'].append(40)
        
        n = random.randint(50,120)
        hun['mlm'].append(n)
        n1 = random.randint(100,200)
        hun['bus'].append(n1)
        n2 = random.randint(0,100)
        hun['moti'].append(n2)
        n3 = random.randint(50,120)
        hun['others'].append(n3)
        hun['clas'].append(40)
    return hun
gg = hundred()
print(len(gg['mlm']))
gg = pd.DataFrame(gg)
gg.to_excel("first_fourty.xlsx")

1000


In [134]:
import random
def hundred():
    hun = {"mlm": [],"bus": [], "moti": [], "others": [], "clas": []}
    mlm = []
    bus = []
    moti = []
    others = []
    clas = []
    for i in range(0,200):
        n = random.randint(0,5)
        hun['mlm'].append(n)
        n1 = random.randint(1,20)
        hun['bus'].append(n1)
        n2 = random.randint(1,15)
        hun['moti'].append(n2)
        n3 = random.randint(25,50)
        hun['others'].append(n3)
        hun['clas'].append(20)
        
        n = random.randint(0,10)
        hun['mlm'].append(n)
        n1 = random.randint(25,50)
        hun['bus'].append(n1)
        n2 = random.randint(0,50)
        hun['moti'].append(n2)
        n3 = random.randint(50,100)
        hun['others'].append(n3)
        hun['clas'].append(20)
        
        n = random.randint(0,10)
        hun['mlm'].append(n)
        n1 = random.randint(50,120)
        hun['bus'].append(n1)
        n2 = random.randint(0,50)
        hun['moti'].append(n2)
        n3 = random.randint(100,200)
        hun['others'].append(n3)
        hun['clas'].append(20)
        
        n = random.randint(0,10)
        hun['mlm'].append(n)
        n1 = random.randint(10,100)
        hun['bus'].append(n1)
        n2 = random.randint(0,50)
        hun['moti'].append(n2)
        n3 = random.randint(200,300)
        hun['others'].append(n3)
        hun['clas'].append(20)
        
        n = random.randint(0,10)
        hun['mlm'].append(n)
        n1 = random.randint(0,100)
        hun['bus'].append(n1)
        n2 = random.randint(0,100)
        hun['moti'].append(n2)
        n3 = random.randint(300,420)
        hun['others'].append(n3)
        hun['clas'].append(20)
    return hun
gg = hundred()
print(len(gg['mlm']))
gg = pd.DataFrame(gg)
gg.to_excel("first_twenty.xlsx")

1000


In [1]:
# Import libraries and classes required for this example:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd 
from sklearn import svm
import pickle
# Import dataset:
#url = “fiveclass_network.xlsx”
from pickle import dump
# Assign column names to dataset:
names = ['mlm', 'bus', 'moti', 'others', 'Clas']

# Convert dataset to a pandas dataframe:
dataset = pd.read_excel("/home/com11/Documents/Network_Propagation/Final_Model/mod.xlsx", names=names) 

# Use head() function to return the first 5 rows: 
dataset.head() 
# Assign values to the X and y variables:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values 

# Split dataset into random train and test subsets:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20) 

# Standardize features by removing mean and scaling to unit variance:
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test) 
dump(scaler, open('scaler.pkl', 'wb'))

#classifier = svm.SVC()
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100) 
classifier.fit(X_train, y_train)
# Use the KNN classifier to fit data:
#classifier = KNeighborsClassifier(n_neighbors=5)
#classifier.fit(X_train, y_train) 
filename = 'finalized_model.pkl'
pickle.dump(classifier, open(filename, 'wb'))# Predict y data with classifier: 
y_predict = classifier.predict(X_test)

# Print results: 
print(confusion_matrix(y_test, y_predict))
print(classification_report(y_test, y_predict)) 


[[185   8   0   0   0]
 [  1 342  53  12   0]
 [  0   5 367  17   5]
 [  0   6  30 271 114]
 [  0   0   2  58 364]]
              precision    recall  f1-score   support

          20       0.99      0.96      0.98       193
          40       0.95      0.84      0.89       408
          60       0.81      0.93      0.87       394
          80       0.76      0.64      0.70       421
         100       0.75      0.86      0.80       424

    accuracy                           0.83      1840
   macro avg       0.85      0.85      0.85      1840
weighted avg       0.84      0.83      0.83      1840



In [4]:
from pickle import load
from sklearn.metrics import accuracy_score
import numpy as np
model = load(open('finalized_model.pkl', 'rb'))
# load the scaler
scaler = load(open('scaler.pkl', 'rb'))
# check scale of the test set before scaling
# transform the test dataset
#X_test_scaled = scaler.transform(X_test)
X_test = np.array([58, 10, 1, 149])
X_test = scaler.transform(X_test.reshape(1, -1))
# make predictions on the test set
#y = model.predict(X_test)
# evaluate accuracy
#acc = accuracy_score(y_test, yhat)
#print('Test Accuracy:', yhat)
#for i in X_test:
y = model.predict(X_test)
print(y)

[20]


In [3]:
import pandas as pd
data = pd.read_excel("fiveclass_network.xlsx")
data = list(data)

In [39]:
data[5:]

[]

In [1]:
# Import libraries and classes required for this example:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd 
from sklearn import svm
import pickle
# Import dataset:
#url = “fiveclass_network.xlsx”
from pickle import dump
# Assign column names to dataset:
names = ['mlm', 'bus', 'moti', 'others', 'Clas']

# Convert dataset to a pandas dataframe:
dataset = pd.read_excel("/home/com11/Documents/Network_Propagation/Final_Model/mod.xlsx", names=names) 

# Use head() function to return the first 5 rows: 
dataset.head() 
# Assign values to the X and y variables:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 4].values 

In [6]:
# Split dataset into random train and test subsets:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20) 

# Standardize features by removing mean and scaling to unit variance:
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test) 
dump(scaler, open('scaler.pkl', 'wb'))

In [7]:
#classifier = svm.SVC()
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 100) 
classifier.fit(X_train, y_train)
# Use the KNN classifier to fit data:
#classifier = KNeighborsClassifier(n_neighbors=5)
#classifier.fit(X_train, y_train) 
filename = 'finalized_model.pkl'
pickle.dump(classifier, open(filename, 'wb'))# Predict y data with classifier: 
y_predict = classifier.predict(X_test)

# Print results: 
print(confusion_matrix(y_test, y_predict))
print(classification_report(y_test, y_predict)) 


[[197   0   0   0   1]
 [  1 403  12   4   0]
 [  0   1 384   3   2]
 [  0   3  11 286  81]
 [  0   1   3  44 403]]
              precision    recall  f1-score   support

          20       0.99      0.99      0.99       198
          40       0.99      0.96      0.97       420
          60       0.94      0.98      0.96       390
          80       0.85      0.75      0.80       381
         100       0.83      0.89      0.86       451

    accuracy                           0.91      1840
   macro avg       0.92      0.92      0.92      1840
weighted avg       0.91      0.91      0.91      1840



In [2]:
from pickle import load
from sklearn.metrics import accuracy_score
import numpy as np
model = load(open('Models/finalized_model.pkl', 'rb'))
# load the scaler
scaler = load(open('Models/scaler.pkl', 'rb'))

# check scale of the test set before scaling
# transform the test dataset
#X_test_scaled = scaler.transform(X_test)
X_test = np.array([10, 1, 12, 32])
print(X_test)
X_test = scaler.transform(X_test.reshape(1, -1))
print(X_test)
# make predictions on the test set
#y = model.predict(X_test)
# evaluate accuracy
#acc = accuracy_score(y_test, yhat)
#print('Test Accuracy:', yhat)
#for i in X_test:
y = model.predict(X_test)
print(y)

[10  1 12 32]
[[-0.46217641 -1.7414622  -0.49919277 -1.15466824]]
[100]


C:\Users\kalaiselvan\Anaconda3\envs\myenv1\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.24.2 when using version 1.1.3. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
C:\Users\kalaiselvan\Anaconda3\envs\myenv1\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.24.2 when using version 1.1.3. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
C:\Users\kalaiselvan\Anaconda3\envs\myenv1\lib\site-packages\sklearn\base.py:329: UserWarning: Trying to unpickle estimator StandardScaler from version 0.24.2 when using version 1.1.3.